name: 'Sync repo to GCS bucket under forlder with repo name'
description: 'Sync a Github repository with folder on a given Google Cloud Storage (GCS) bucket. The folder name is the repo name.'
author: 'jmbenedetto'

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: Bucket name
    required: true
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: '.git$'

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: gray-dark
